<?php

namespace Database\Seeders;

use App\Models\User;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $json = File::get('database/json/StudentModel.json');
        $data = collect(json_decode($json, true));

        $data->each(function($single){
            User::insert($single);
        });

        $records = collect([
            [
                'name' => 'Rofiqual Islam',
                'name_bn' => 'রফিকুল ইসলাম',
                'password' => Hash::make('123'),
                'email' => 'sirikotiamadrasha@gmail.com',
                'role' => 'admin',
                'contact_sms' => '01892178778',
                'contact_whatsapp' => '01892178778',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'married',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '2577534',
                'profile_pic' => 'img/users/rofiq.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Anisur Rahman',
                'name_bn' => 'আনিসুর রহমান',
                'password' => Hash::make('123'),
                'email' => 'anis14109@gmail.com',
                'role' => 'admin',
                'contact_sms' => '01871123427',
                'contact_whatsapp' => '01871123427',
                'sms_status' => 'on',
                'nid' => '4202555860',
                'birth_reg' => '',
                'date_of_birth' => '1997-12-01',
                'gender' => 'male',
                'blood_group' => 'A+',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'married',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '2577217',
                'profile_pic' => 'img/users/anis.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '2025-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nurun Nabi',
                'name_bn' => 'নুরুন নবী',
                'password' => Hash::make('123'),
                'email' => 'nurnabi@gmail.com',
                'role' => 'admin',
                'contact_sms' => '01621986417',
                'contact_whatsapp' => '01621986417',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'single',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '2569950',
                'profile_pic' => 'img/users/nurnabi.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sadrul Ula',
                'name_bn' => 'ছদরুল উলা',
                'password' => Hash::make('123'),
                'email' => 'sadrulula@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '01735646953',
                'contact_whatsapp' => '01735646953',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'married',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '',
                'profile_pic' => 'img/users/sadrulula.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Habibur Rahman',
                'name_bn' => 'হাবিবুর রহমান',
                'password' => Hash::make('123'),
                'email' => 'habiburrahman@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '01581738726',
                'contact_whatsapp' => '01581738726',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'married',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '',
                'profile_pic' => 'img/users/habibullah.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Farzana Akter',
                'name_bn' => 'ফারজানা আক্তার',
                'password' => Hash::make('123'),
                'email' => 'farzana@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '00000000000',
                'contact_whatsapp' => '00000000000',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'married',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '',
                'profile_pic' => 'img/users/farzana.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nasrin Akther',
                'name_bn' => 'নাসরিন আক্তার',
                'password' => Hash::make('123'),
                'email' => 'nasrin@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '01610949736',
                'contact_whatsapp' => '01610949736',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'married',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '',
                'profile_pic' => 'img/users/nasrin.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rasheda Akther',
                'name_bn' => 'রাশেদা আক্তার',
                'password' => Hash::make('123'),
                'email' => 'rasheda@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '01864755915',
                'contact_whatsapp' => '01864755915',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'married',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '',
                'profile_pic' => 'img/users/rasheda.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sufia Akther Simi',
                'name_bn' => 'সুফিয়া আক্তার সিমি',
                'password' => Hash::make('123'),
                'email' => 'sufia@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '01835905440',
                'contact_whatsapp' => '01835905440',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'married',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '',
                'profile_pic' => 'img/users/sufia.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Abdur Rahim',
                'name_bn' => 'আব্দুর রহিম',
                'password' => Hash::make('123'),
                'email' => 'abdur@gmail.com',
                'role' => 'security',
                'contact_sms' => '01854351399',
                'contact_whatsapp' => '',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'married',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '2575433',
                'profile_pic' => 'img/users/000.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

         $records->each(function($data){
            User::insert($data);
        });

    }
}
