<?php

namespace Database\Seeders;

use App\Models\User;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;

class UsersTeachersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $records = collect([
            [
                'name' => 'Sadrul Ula',
                'name_bn' => 'ছদরুল উলা',
                'password' => Hash::make('123'),
                'email' => 'sadrulula@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '01735646953',
                'contact_whatsapp' => '01735646953',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'married',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '',
                'profile_pic' => 'img/users/sadrulula.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Habibur Rahman',
                'name_bn' => 'হাবিবুর রহমান',
                'password' => Hash::make('123'),
                'email' => 'habiburrahman@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '01581738726',
                'contact_whatsapp' => '01581738726',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'married',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '',
                'profile_pic' => 'img/users/habibullah.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Farzana Akter',
                'name_bn' => 'ফারজানা আক্তার',
                'password' => Hash::make('123'),
                'email' => 'farzana@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '00000000000',
                'contact_whatsapp' => '00000000000',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'married',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '',
                'profile_pic' => 'img/users/farzana.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nasrin Akther',
                'name_bn' => 'নাসরিন আক্তার',
                'password' => Hash::make('123'),
                'email' => 'nasrin@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '01610949736',
                'contact_whatsapp' => '01610949736',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'married',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '',
                'profile_pic' => 'img/users/nasrin.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rasheda Akther',
                'name_bn' => 'রাশেদা আক্তার',
                'password' => Hash::make('123'),
                'email' => 'rasheda@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '01864755915',
                'contact_whatsapp' => '01864755915',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'married',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '',
                'profile_pic' => 'img/users/rasheda.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sufia Akther Simi',
                'name_bn' => 'সুফিয়া আক্তার সিমি',
                'password' => Hash::make('123'),
                'email' => 'sufia@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '01835905440',
                'contact_whatsapp' => '01835905440',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'married',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '',
                'profile_pic' => 'img/users/sufia.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Abdur Rahim',
                'name_bn' => 'আব্দুর রহিম',
                'password' => Hash::make('123'),
                'email' => 'abdur@gmail.com',
                'role' => 'security',
                'contact_sms' => '01854351399',
                'contact_whatsapp' => '',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'married',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '2575433',
                'profile_pic' => 'img/users/000.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

         $records->each(function($data){
            User::insert($data);
        });

    }
}
