<?php

namespace Database\Seeders;

use App\Models\User;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $records = collect([
            [
                'name' => 'MD. ROFIKUL ISLAM',
                'name_bn' => 'মোঃ রফিকুল ইসলাম',
                'password' => Hash::make('12345678'),
                'email' => 'sirikotiamadrasha@gmail.com',
                'role' => 'admin',
                'contact_sms' => '01892178778',
                'contact_whatsapp' => '01892178778',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'married',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '2577534',
                'profile_pic' => 'img/users/rofiq.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'NURUN NABI',
                'name_bn' => 'নুরুন নবী',
                'password' => Hash::make('12345678'),
                'email' => 'azimahmed973@gmail.com',
                'role' => 'admin',
                'contact_sms' => '01621986417',
                'contact_whatsapp' => '01621986417',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'single',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '2569950',
                'profile_pic' => 'img/users/nurnabi.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sadrul Ula',
                'name_bn' => 'ছদরুল উলা',
                'password' => Hash::make('123'),
                'email' => 'sadrulula@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '01735646953',
                'contact_whatsapp' => '01735646953',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'married',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '',
                'profile_pic' => 'img/users/sadrulula.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MD NAHIM',
                'name_bn' => 'মোঃ নাহিম',
                'password' => Hash::make('123'),
                'email' => 'nahim@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '01342-665105',
                'contact_whatsapp' => '01342-665105',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'single',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '0002279398',
                'profile_pic' => 'img/users/nahim.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MD SHA JALAL HOSSAIN',
                'name_bn' => 'মোঃ শাহ্ জালাল হোসাইন',
                'password' => Hash::make('123'),
                'email' => 'shajalal@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '01600-139107',
                'contact_whatsapp' => '01600-139107',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'single',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '0002244288',
                'profile_pic' => 'img/users/shajalal.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MD. RASHEDUL ISLAM',
                'name_bn' => 'মোঃ রাশেদুল ইসলাম',
                'password' => Hash::make('123'),
                'email' => 'rashedul@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '01585-774251',
                'contact_whatsapp' => '01585-774251',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'single',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '0001937046',
                'profile_pic' => 'img/users/rashedul.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MOHAMMAED JABED HOSSEN',
                'name_bn' => 'মুহাম্মদ জাবেদ হোসেন',
                'password' => Hash::make('123'),
                'email' => 'jabed@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '01890-084464',
                'contact_whatsapp' => '01890-084464',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'single',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '0004015357',
                'profile_pic' => 'img/users/jabed.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Anisur Rahman',
                'name_bn' => 'আনিসুর রহমান',
                'password' => Hash::make('123'),
                'email' => 'anis14109@gmail.com',
                'role' => 'admin',
                'contact_sms' => '01871-123427',
                'contact_whatsapp' => '01871-123427',
                'sms_status' => 'on',
                'nid' => '4202555860',
                'birth_reg' => '',
                'date_of_birth' => '1997-12-01',
                'gender' => 'male',
                'blood_group' => 'A+',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'married',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '2577217',
                'profile_pic' => 'img/users/anis.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '2025-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ABDUR RAHIM',
                'name_bn' => 'আবদুর রহিম',
                'password' => Hash::make('123'),
                'email' => 'rahim@gmail.com',
                'role' => 'Security',
                'contact_sms' => '01854-351399',
                'contact_whatsapp' => '01854-351399',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'male',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'single',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '0001927536',
                'profile_pic' => 'img/users/rahim.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'MRS. RASHEDA AKHTER',
                'name_bn' => 'মোছাঃ রাশেদা আকতার',
                'password' => Hash::make('123'),
                'email' => 'rasheda@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '01864-755915',
                'contact_whatsapp' => '01864-755915',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'female',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'single',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '',
                'profile_pic' => 'img/users/rasheda.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SUFIA AKHTER SIMI',
                'name_bn' => 'সুফিয়া আক্তার সিমি',
                'password' => Hash::make('123'),
                'email' => 'sufia@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '01835-905440',
                'contact_whatsapp' => '01835-905440',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'female',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'single',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '',
                'profile_pic' => 'img/users/sufia.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'FARZANA AKTER',
                'name_bn' => 'ফারজানা আক্তার',
                'password' => Hash::make('123'),
                'email' => 'farzana@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '01890-253915',
                'contact_whatsapp' => '01890-253915',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'female',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'single',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '',
                'profile_pic' => 'img/users/farzana.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ANY AKTHER',
                'name_bn' => 'এ্যানি আক্তার',
                'password' => Hash::make('123'),
                'email' => 'anyakther@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '01866-797370',
                'contact_whatsapp' => '01866-797370',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'female',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'single',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '0004038581',
                'profile_pic' => 'img/users/anyakther.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'RABEYA SULTANA MAISHA',
                'name_bn' => 'রাবেয়া সুলতানা মাইশা',
                'password' => Hash::make('123'),
                'email' => 'maisha@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '01814-863851',
                'contact_whatsapp' => '01814-863851',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'female',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'single',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '0002170180',
                'profile_pic' => 'img/users/maisha.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
           [
                'name' => 'JANNATUL FERDAOUS TISHA',
                'name_bn' => 'জান্নাতুল ফেরদৌস তিশা',
                'password' => Hash::make('123'),
                'email' => 'tisha@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '01860-363932',
                'contact_whatsapp' => '01860-363932',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'female',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'single',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '0004048300',
                'profile_pic' => 'img/users/tisha.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SHAHANAJ SULTANA',
                'name_bn' => 'শাহানাজ সুলতানা',
                'password' => Hash::make('123'),
                'email' => 'shahanaj@gmail.com',
                'role' => 'teacher',
                'contact_sms' => '01876-054753',
                'contact_whatsapp' => '01876-054753',
                'sms_status' => 'on',
                'nid' => '',
                'birth_reg' => '',
                'date_of_birth' => '',
                'gender' => 'female',
                'blood_group' => '',
                'health_issues' => '',
                'height' => '',
                'weight' => '',
                'marital_status' => 'single',
                'nationality' => '',
                'religion' => '',
                'present_address' => '',
                'permanent_address' => '',
                'rfid_card' => '0002293186',
                'profile_pic' => 'img/users/shahanaj.png',
                'signature' => '',
                'status' => 'active',
                'joined_at' => '',
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);

         $records->each(function($data){
            User::insert($data);
        });

    }
}
